In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv("https://raw.githubusercontent.com/slmsshk/DataSet/main/airline-passengers.csv")
df

       Month  Passengers
0    1949-01         112
1    1949-02         118
2    1949-03         132
3    1949-04         129
4    1949-05         121
..       ...         ...
139  1960-08         606
140  1960-09         508
141  1960-10         461
142  1960-11         390
143  1960-12         432

[144 rows x 2 columns]

In [ ]:

df['year'] = pd.DatetimeIndex(df['Month']).year
df['month'] = pd.DatetimeIndex(df['Month']).month

In [ ]:
df

       Month  Passengers  year  month
0    1949-01         112  1949      1
1    1949-02         118  1949      2
2    1949-03         132  1949      3
3    1949-04         129  1949      4
4    1949-05         121  1949      5
..       ...         ...   ...    ...
139  1960-08         606  1960      8
140  1960-09         508  1960      9
141  1960-10         461  1960     10
142  1960-11         390  1960     11
143  1960-12         432  1960     12

[144 rows x 4 columns]

In [ ]:
x=df[[df.columns[-1]]]
y=df["Passengers"]

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=20,random_state=2)

In [ ]:
from sklearn.tree import DecisionTreeRegressor

In [ ]:
dtr=DecisionTreeRegressor(min_samples_split=6)

In [ ]:
x_train.shape

(124, 1)

In [ ]:
dtr.fit((x_train),y_train)

DecisionTreeRegressor(min_samples_split=6)

In [ ]:
dtr.score(x_test,y_test)

0.9887879626579044

In [ ]:
from sklearn.metrics import mean